# **Concatenación de arreglos**


La concatenación, o unión de dos arreglos en NumPy, se realiza principalmente a través de la función `concatenate`:

In [4]:
import numpy as np

In [1]:
#Concatenación de listas
x = [1, 2, 3]
y = [4, 5, 6]

x + y

[1, 2, 3, 4, 5, 6]

In [5]:
#Concatenación en numpy

xa = np.array(x)
ya = np.array(y)

np.concatenate((xa, ya))

array([1, 2, 3, 4, 5, 6])

Podemos concatenar más de dos arreglos al tiempo:

In [6]:
za = np.array([7, 8, 9])

np.concatenate((xa, ya, za))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`concatenate` también se puede usar para arreglos bidimensionales. Recuerde que las filas corresponden al eje 1 (axis = 1) y las columnas al eje 0 (axis = 0)


<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/KYPgvhf.png" align="left" hspace="10px" vspace="0px"></p>

In [8]:
a = np.arange(8, 14).reshape(3, 2)
a

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [9]:
np.concatenate((a,a), axis = 0)

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [ 8,  9],
       [10, 11],
       [12, 13]])

Si queremos realizar la concatenación a lo largo del eje 1, debemos especificar el eje por medio de un argumento por palabra clave:

In [10]:
np.concatenate((a,a), axis = 1)

array([[ 8,  9,  8,  9],
       [10, 11, 10, 11],
       [12, 13, 12, 13]])

La función `vstack()` es equivalente a la concatenación a lo largo del primer eje (axis=0). Al igual que `concatenate()`, recibe como argumento una secuencia de arreglos que, en este caso, deben tener la misma forma a lo largo de todos los ejes, excepto el primero. Los arreglos unidimensionales deben tener la misma longitud:

In [11]:
# dimensiones mixtas
a = np.array([1, 2, 3])
b = np.arange(4, 10).reshape(2, 3)

print(a)
print(b)

[1 2 3]
[[4 5 6]
 [7 8 9]]


In [12]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#No se puede hacer si presentan dimensionalidad diferente
try:
    np.hstack((a, b))
except Exception as e:
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)


Similarmente, la función `hstack()` realiza una concatenación a lo largo del segundo eje (axis=1), y los arreglos que toma como argumento deben coincidir en la forma a lo largo de este eje. Los arreglos unidimensionales pueden ser de cualquier longitud

In [16]:
#dimensiones mixtas
a = np.array([[1, 2], [3, 4]])


In [17]:
#arreglos unidimensionales
np.hstack((a, b))

array([[1, 2, 4, 5, 6],
       [3, 4, 7, 8, 9]])

### **Slicing o segmentación en Python**

```
l[inicio: final(no incluyente): paso]
```

In [44]:
l = list(range(10, 160, 10))
l

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]

In [45]:
l[0 : 5]

[10, 20, 30, 40, 50]

In [46]:
l[ : 5]

[10, 20, 30, 40, 50]

In [47]:
l[8: 16]

[90, 100, 110, 120, 130, 140, 150]

In [48]:
l[8: ]

[90, 100, 110, 120, 130, 140, 150]

In [49]:
l[8:12]

[90, 100, 110, 120]

In [50]:
l[4: 16: 2]

[50, 70, 90, 110, 130, 150]

In [57]:
l[-3 : ]

[130, 140, 150]

<p><a name="ind"></a></p>

# **Indexación y segmentación**

Los arreglos de NumPy tienen la misma semántica de indexación y segmentación que las listas de Python cuando se trata de acceder a elementos o subarreglos.




In [19]:
a = np.arange(8)

print(f"a: {a}")
print(f"a[2]: {a[2]}") #Indexación
print(f"a[2:5]: {a[2:5]}") #Segmentación

a: [0 1 2 3 4 5 6 7]
a[2]: 2
a[2:5]: [2 3 4]


Debido a que los arreglos de NumPy son n-dimensionales, podemos segmentar a lo largo de todos y cada uno de los ejes. Consideremos la siguiente lista de listas en Python

In [23]:
# definiendo una lista de listas de forma (3,3)
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Por ejemplo, si queremos crear una lista de Python que contenga todas las filas y las primeras dos columnas de la lista L podríamos escribir

In [24]:
[sub_l[ : 2] for sub_l in l]

[[1, 2], [4, 5], [7, 8]]

El número de ciclos `for` anidados que se necesita para segmentar listas de listas es igual al número de dimensiones menos uno (en este caso $2-1=1$).

En NumPy, en lugar de indexar por un segmento, podemos indexar por una tupla de segmentos, cada uno de los cuales actúa en sus propias dimensiones. Definamos el arreglo `L` con NumPy y realicemos la segmentación anterior:


In [25]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Los ciclos `for` para la segmentación multidimensional son manejados implícitamente por NumPy. Esto hace que realizar segmentaciones complejas sea mucho más rápido que escribir los ciclos `for` explícitamente en Python. Veamos algunos ejemplos:

In [28]:
#creamos un arreglo de dimensiones 4x4
a = np.arange(1, 17).reshape(4, 4)

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
np.arange(1, 5).reshape(4,1)#.ndim

array([[1],
       [2],
       [3],
       [4]])

In [31]:
#seleccionar la primer fila (equivalente a a[0,:])
a[0]

array([1, 2, 3, 4])

In [32]:
# seleccionar la primera columna
a[:, 0]

array([ 1,  5,  9, 13])

In [58]:
#segmentar las filas pares y las columnas impares.
a[::2, 1::2]

array([[ 2,  4],
       [10, 12]])

In [59]:
#segmentar la matriz interna de 2x2.
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [61]:
#invertir las primeras 3 filas, tomando las primeras 3 columnas
a[2 : : -1, :3]

array([[ 9, 10, 11],
       [ 5,  6,  7],
       [ 1,  2,  3]])

**Ejercicio 1**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>

In [63]:
a = np.array([1,2,3,2,4,6,1,2,12,0,-12,6])
a = a.reshape(4,3)
print(a)
#np.mean(a, axis = 1)

[[  1   2   3]
 [  2   4   6]
 [  1   2  12]
 [  0 -12   6]]


In [66]:
np.mean(a, axis = 1)

array([ 2.,  4.,  5., -2.])

<p><a name="enm"></a></p>

## **Enmascaramiento**

El enmascaramiento aparece cuando deseamos extraer, modificar, o manipular valores en un arreglo de acuerdo con algún criterio.

Ya vimos cómo utilizar ufuncs para operaciones aritméticas básicas y otro tipo de operaciones más complejas. NumPy implementa también operadores de comparación como ufuncs:

In [67]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
x < 6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

El resultado es un arreglo booleano. Dado un arreglo booleano, hay una serie de operaciones útiles que podemos implementar.

Podemos utilizar la función `np.sum` junto con los operadores de comparación para realizar conteos dentro del arreglo:

In [69]:
# numero de elementos menores a 6
np.sum(x < 6)

5

Con `np.sum` podemos realizar este tipo de conteos a lo largo de las filas o columnas, utilizando el argumento por palabra clave `axis`:

In [70]:
# numero de elementos menores a 6 por columna
np.sum(x < 6, axis = 0)

array([2, 2, 1])

In [71]:
# numero de elementos menores a 6 por fila
np.sum(x < 6, axis = 1)

array([3, 2, 0])

Podemos también tener múltiples condiciones en un conteo, utilizando los operadores lógicos `&` (and) y `|` (or)

In [75]:
# verdadero si ambos verdaderos
print((x > 1) & (x < 6))
np.sum((x > 1) & (x < 6))

[[False False  True]
 [ True  True False]
 [False False False]]


3

In [77]:
# verdadero en caso en que alguno de los dos sea verdadero
print((x < 2) | (x > 6))
np.sum((x < 2) | (x > 6))

[[ True False False]
 [False False False]
 [ True  True  True]]


4

Una herramienta muy poderosa es usar los arreglos booleanos como máscaras, para seleccionar subconjuntos particulares de los datos mismos.

Volviendo a nuestra arreglo `x` anterior, supongamos que queremos un arreglo de todos los valores en `x` que sean menores que, digamos, 5. Para seleccionar estos valores del arreglo, simplemente podemos indexar con este arreglo booleano; esto se conoce como una operación de enmascaramiento:

In [80]:
x < 6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [83]:
x[ x < 7]

array([1, 2, 3, 4, 5, 6])

Lo que se devuelve es un arreglo unidimensional con todos los valores que cumplen la condición; en otras palabras, todos los valores en las posiciones en las que el arreglo de máscara es `True`.

**Ejercicio 2:** Escriba una función que, dado un número entero `n`, retorne:

* Un arreglo con los primeros números pares hasta `n`, incluyendo.
* Un arreglo con los primeros números múltiplos de tres hasta `n`, incluyendo.

<p><a name="sof"></a></p>

# **Indexación sofisticada**

Anteriormente vimos cómo acceder y modificar porciones de arreglos usando índices simples (por ejemplo, `arr[0]`), segmentos (por ejemplo, `arr[: 5]`) y máscaras booleanas (por ejemplo, `arr[arr> 0]`). Veremos ahora otro estilo de indexación de arreglos, conocido como *indexación sofisticada*, la cual nos permite acceder y modificar muy rápidamente subconjuntos complicados de los valores de un arreglo.

La indexación sofisticada es conceptualmente simple: significa pasar una lista de índices en lugar de un entero, para acceder a múltiples elementos del arreglo a la vez. Veamos un ejemplo:

In [85]:
a = np.arange(10, 21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [86]:
np.array([a[0], a[2], a[7]])

array([10, 12, 17])

In [87]:
indi = [0, 2, 7]

a[indi]

array([10, 12, 17])

Con el indexado sofisticado, la forma del resultado refleja la forma del arreglo de índices más que la forma del arreglo que se está indexando:

In [89]:
a = np.arange(0, 91, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
ind = np.array([[3, 7], [5, 8]])
a[ind]

array([[30, 70],
       [50, 80]])

El indexado sofisticado funciona también en múltiples dimensiones. Veámoslo en el siguiente ejemplo:

In [91]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Como en la indexación estándar, el primer índice hace referencia a las filas y el segundo a las columnas:

In [92]:
fila = [0, 1, 2]
colu = [2, 1, 3]
a[fila, colu]

array([ 2,  5, 11])

In [94]:
np.array([a[0,2], a[1,1], a[2, 3]])

array([ 2,  5, 11])

Los valores el en arreglo corresponden a `a[0,2]`, `a[1,1]` y `a[2,3]` respectivamente.